server:
  port: 9999
dubbo:
  # 应用名称
  application:
    name: boot-order-service-consumer
  # 注册中心
  registry:
    address: zookeeper://127.0.0.1:2181
  # 消费者的统一配置
  consumer:
    # 默认值 true
    check: false
    # 默认值 1000，单位ms
    timeout: 1000